### ISSUE TITLE
doesn't remember color selection after PC restart

### ISSUE THREAD

**Issue by ayhanyildiz** [SasaKaranovic/VU-Demo-App#5]
Thanks for sharing this lovely app. I have one issue; After restarting my PC it doesn't remember color selections. Am I missing something or it is not baked in yet?

**Comment by SasaKaranovic** [comment]
@ayhanyildiz Setting the color is meant to be "temporary" or just for testing how the dials look.
If you setup a rule (even if it's just for one single color), it will persist through power cycle and be applied every time the application starts.

**Comment by ayhanyildiz** [comment]
thanks @SasaKaranovic. that helps.
